# Generated by Django 2.0.4 on 2018-05-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'bulletin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('pic', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('locationrange', models.CharField(blank=True, max_length=1, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readed',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'readed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('username', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=5)),
                ('activated', models.CharField(max_length=1)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
